CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
category VARCHAR(255),
status BOOLEAN NOT NULL DEFAULT false,
user_id INTEGER REFERENCES users(id)
);
